### ISSUE TITLE
Wrong config paths

### ISSUE THREAD

**Issue by EmilioAiolfi** [micahgodbolt/grunt-phantomcss#1]
Hello @micahgodbolt micahgodbolt,
I can not create specific ways of screenshots or results. For all paths is based on the way the 'src'.

Is this right?

When an image is not equal and there is failure, the screenshot folder is recreated at the root ...

Tks

**Comment by mbehzad** [comment]
+1

**Comment by micahgodbolt** [comment]
hey @EmilioAiolfi can you post in your grunt config info? Also, remember that the results are going to be created in the same folder as your test code.
