### ISSUE TITLE
path.dirname is undefined

### ISSUE THREAD

**Issue by andi1984** [micahgodbolt/grunt-phantomcss#13]
Inside phantomjs runner.js ``path.dirname(testSuite)`` is undefined inside my grunt project. Any hints what's going wrong there?

OS: Mac OSX
Node Version: 0.12.2
NPM Version: 2.7.4

My Grunt Task:

```coffee
phantomcss:
      options:
        baselines: 'screenshots/',
        results: 'results/'
        viewportSize: [1280, 800],
        mismatchTolerance: 0.05
      dev:
        src: ['tests/visual/*.js']
```

The path tests/visual/ exists and isn't empty.

**Comment by austinmcorso** [comment]
@andi1984 does this fix your issue?
```
    phantomcss: {
      options: {
        baselines: 'screenshots/',
        results: 'results/'
        viewportSize: [1280, 800],
        mismatchTolerance: 0.05
      },
      src: ['./tests/visual/*.js']
   },
```

**Comment by andi1984** [comment]
@austinmcorso Nope, unfortunately not. Testet this already before posting the issue.

**Comment by micahgodbolt** [comment]
Can you try pointing it at an explicit filename? The error certainly is saying it can't find any test files.

**Comment by andi1984** [comment]
@micahgodbolt Doesn't work either. I've to mention that the tests always executed correctly. In the specific and less-specific ``src`` definition. But with the above example in mind the ``undefinedscreenshots`` folder is created and filled with correct images. But the foldername, especially the ```phantomcss.pathToTest```, is still 'undefined'. Any hints what's wrong there?

**Comment by andi1984** [comment]
Update:

I've debugged the ``runner.js`` file inside your phantomjs subdirectory.

```javascript
// Run the test scenarios
args.test.forEach(function(testSuite) {
  phantom.casperTest = true;
  phantom.rootUrl = args.rootUrl;
  casper.then(function() {
    // 1 - this should be applied, shouldn't it`
    phantomcss.pathToTest = path.dirname(testSuite) + '/';
  });
  require(testSuite);
  casper.then(function() {
    // 2
    phantomcss.compareSession();
  })
  .then(function() {
    // 3
    casper.test.done();
  });
});
```

Only comment 2 and 3 are reached, **but not comment 1**, hence phantomcss.pathToTest is always undefined. Any hints why // 1 is never reached?

**Comment by axe312ger** [comment]
Also the baseURL parameter is not working anymore :(

**Comment by andi1984** [comment]
@axe312ger Did you get it working again?

Generally any updates based on this issue?

**Comment by axe312ger** [comment]
Nope, i hacked the baseURL in the casperjs tests to get it working for the customer... 

@micahgodbolt can you please test your code on a fresh install? Based on your example in the readme, it is not working :(

**Comment by micahgodbolt** [comment]
@axe312ger that readme REALLY needs to be updated. It's leftover from the original module author. You are trying to get the baseURL working, correct? How are you trying to use it? It was a requested feature and it simply passes a string value into the casper test files to be concatenated with your URL. It doesn't magically prepend or anything.

**Comment by micahgodbolt** [comment]
@axe312ger the readme has been updated with examples of how to use baseURL. Does this help?

**Comment by axe312ger** [comment]
@micahgodbolt Yes, that helped a lot. I could now remove some hacks and the whole stuff is running smoother.

I still have problems with the paths of "screenshot" and "result". Its not working like in the example and not like I interpret the infos in the options description section in the readme. It looks like "results" is completely ignored (it uses the value from "screenshots").

**Comment by micahgodbolt** [comment]
@axe312ger i've noticed that bug too. i'll open a separate issue. Should we consider this current issue closed then?
