### ISSUE TITLE
Task failing with npm 3.4.0

### ISSUE THREAD

**Issue by danieltott** [micahgodbolt/grunt-phantomcss#6]
Been trying for a couple hours to get this working, but I'm having some issues.  I started a fresh project to make sure nothing I had set up before was messing up.

So - I'm on npm 3.4.0, node v4.2.1, Grunt 0.4.5

My Gruntfile: 

``` javascript
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    phantomcss: {
      options: {
          screenshots: 'test/visual/screenshots/',
          results: 'results/visual/',
          viewportSize: [1280, 800],
          mismatchTolerance: 0.05,
          rootUrl: 'http://localhost:3000/' // Optional
        },
        src: [
          'test/visual/**/*.js'
        ]
      }

  });

  // Load the plugin that provides the "uglify" task.
  grunt.loadNpmTasks('grunt-phantomcss');

  // Default task(s).
  grunt.registerTask('default', ['phantomcss']);

};
```

Running `grunt phantomcss` with this setup gives me this error message: `Local Npm module "grunt-phantomcss" not found. Is it installed?`

If I change `grunt.loadNpmTasks('grunt-phantomcss');` to `grunt.loadNpmTasks('@micahgodbolt/grunt-phantomcss');`, the task runs, but then outputs this:

```
Error: Cannot find module 'casper'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /sprokets/testing/phantomcss/node_modules/@micahgodbolt/grunt-phantomcss/phantomjs/runner.js:39
```

I started digging around in the code trying to change `phantomCSSPath`, `phantom.casperPath`, etc, to no avail. I was able to get different error messages, all of which were about not being able to find one package or another.

It seems like the original task is looking for packages inside of `/node_modules/@micahgodbolt/grunt-phantomcss/node_modules`, but this directory simple doesn't exist in my setup. I can see casperjs and phantomcss directly in `node_modules`, but the grunt task runner isn't able to get to them for some reason. I suspect it has something to do with the scoping, but my lack of npm package development is limiting my ability to diagnose the problem any further.

If some light could be shed on this, that would be awesome!

**Comment by callummr** [comment]
Hey @danieltott. I had the same issue. The workaround I'm currently using is an npm `postinstall` script I added to my package (which depends on this one). It jumps in to the directory it's looking for casper in and runs `npm install` so it will be present.

Here's the excerpt from my `package.json` which gets the job done:

``` JSON
"scripts": {
    "postinstall": "cd node_modules\\@micahgodbolt\\grunt-phantomcss && npm install && cd node_modules\\phantomcss && npm install"
  },
```

If you're just using this actual package rather than it being a dependency of something you're working on, then you should only need to run `cd node_modules\phantomcss && npm install`.

I need to fix this properly and make a PR but it's not priority right now, hopefully this can help you out in the meantime.

**Comment by micahgodbolt** [comment]
hmm...I'll take a look at this soon, see what I can do.

**Comment by zrothauser** [comment]
I'm having this issue as well, but the postinstall script doesn't work for me. Going into the grunt-phantomcss directory and manually running `npm install` doesn't fix it for me either. 

```
Error: Cannot find module 'casper'

    phantomjs://bootstrap.js:289
    phantomjs://bootstrap.js:254 in require
    /Users/zrothauser/vagrant-local/www/test/htdocs/wp-content/themes/test/node_modules/@micahgodbolt/grunt-phantomcss/phantomjs/runner.js:39
```

**Comment by zrothauser** [comment]
I had to downgrade node/npm to get this working again (currently using node 0.12.9).

When running `npm install` with the older version, I get this deprecation warning:

```
WARN peerDependencies The peer dependency phantomjs@^1.9.7-14 included from @micahgodbolt/grunt-phantomcss will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

It looks like the use of peer dependencies may be what causes this problem in npm 3+?

**Comment by micahgodbolt** [comment]
Yup, sadly there was an architectural decision in the original project that assumes node modules are local to this module. It'll either need some major rework, or need to figure out if we can force that casperjs dependency to get loaded INTO the phantomcss module.

**Comment by rh1811** [comment]
Will there be a fix for that?

Still getting stuck with "Error: Cannot find module 'casper'"

**Comment by builtbyjay** [comment]
Replacing the `\\` with `/` in that postinstall script worked for me. Thanks @callummr

**Comment by callummr** [comment]
Ah of course, we use Windows at work so the path is written differently @builtbyjay. Glad that helped you!

**Comment by micahgodbolt** [comment]
@rh1811 I'm open to pull requests for sure, but I dont' know when I'm going to get time to make this work for newer versions of Node. The code in question is inherited from the original project, so it'd take quite a bit of time to refactor.

**Comment by rlamorea** [comment]
It would seem the quick and dirty thing to do is just add an option to be able to override the default location of Casper and then you can configure it in the gruntfile.

I'll see if I can't put together a pull request to do that.

**Comment by micahgodbolt** [comment]
This should be resolved now.
