### ISSUE TITLE
httpS isn't working

### ISSUE THREAD

**Issue by c0nstantine** [micahgodbolt/grunt-phantomcss#7]
I was trying to test httpS resources, but I get that error:
[warning] [phantom] Loading resource failed with status=fail:

you can see that issue with https://www.facebook.com

thanks in advance!

**Comment by micahgodbolt** [comment]
i don't see this as a grunt issue. Would probably be up the chain a bit more.

**Comment by c0nstantine** [comment]
Hey Micah, thank you very much for the quick response, is there any chance to test httpS urls ? bc it says -- PhantomJS updated to v1.98 to fix SSLv3 bug

thanks for the help!

**Comment by linavegiene** [comment]
Tiago has added a pull request to get around this problem.
https://github.com/micahgodbolt/grunt-phantomcss/pull/11
